worker_processes 4;

events {
  worker_connections 1024;
}

http {

  upstream app_servers {
    server ctfd:8000;
  }

  # Redirect HTTP -> HTTPS
  server {
    listen 80;
    server_name whatdahack.com www.whatdahack.com;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name whatdahack.com www.whatdahack.com;

    ssl_certificate     /etc/letsencrypt/live/whatdahack.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/whatdahack.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    gzip on;
    client_max_body_size 4G;

    location /events {
      proxy_pass http://app_servers;
      proxy_set_header Connection "";
      proxy_http_version 1.1;
      chunked_transfer_encoding off;
      proxy_buffering off;
      proxy_cache off;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass http://app_servers;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
